id: opecha:P000338
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS44552
  title: ཟི་ལིང་བཀྲ་ཤིས་གླིང་ཀའི་བྱང་ཆུབ་མཆོད་རྟེན་ཆེན་མོ་གསར་བཞེངས་ཀྱི་དཀར་ཆག
  volume:
    017c292b8c2b43d09c6648a8b04e9842:
      image_group_id: I1GS44556
      title: Volume 1 of zi ling bkra shis gling ka'i byang chub mchod rten chen mo
        gsar bzhengs kyi dkar chag
      volume_number: 1
      total_pages: 33
  author: ''
ebook_metadata:
  title: ཟི་ལིང་བཀྲ་ཤིས་གླིང་ཀའི་བྱང་ཆུབ་མཆོད་རྟེན་ཆེན་མོ་གསར་བཞེངས་ཀྱི་དཀར་ཆག
  author: ''
  sku: P000338
  cover: cover.jpg
  layers:
  - pagination
