id: P000338
initial_creation_type: ocr
created_at: 13/03/2020
last_modified_at: 2021-12-16 15:34:46.330431
source_metadata:
  id: bdr:W1GS44552
  title: ཟི་ལིང་བཀྲ་ཤིས་གླིང་ཀའི་བྱང་ཆུབ་མཆོད་རྟེན་ཆེན་མོ་གསར་བཞེངས་ཀྱི་དཀར་ཆག
  author: ''
  volumes:
    017c292b8c2b43d09c6648a8b04e9842:
      image_group_id: I1GS44556
      title: Volume 1 of zi ling bkra shis gling ka'i byang chub mchod rten chen mo
        gsar bzhengs kyi dkar chag
      volume_number: 1
      total_pages: 33
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
